name: linux-cxx20-conan

on: [push]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: llvm
            compiler-version: 16
          - compiler: llvm
            compiler-version: 18
          - compiler: gcc
            compiler-version: 11
            additional-dep: "g++-11"
          - compiler: gcc
            compiler-version: 12
          - compiler: gcc
            compiler-version: 14
          - compiler: llvm
            compiler-version: 16
          - compiler: llvm
            compiler-version: 18
          - compiler: gcc
            compiler-version: 11
            additional-dep: "g++-11"
          - compiler: gcc
            compiler-version: 12
          - compiler: gcc
            compiler-version: 14
    name: "${{ github.job }} (${{ matrix.compiler }}-${{ matrix.compiler-version }})"
    runs-on: ubuntu-latest
    steps:
      - name: Install Conan 
        run: |
          pipx install conan
          conan profile detect
      - name: Compile
        run: conan build . --build=missing -s compiler.cppstd=gnu20
