name: linux-cxx20-conan

on: [push]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: llvm
            compiler-version: 16
          - compiler: llvm
            compiler-version: 18
          - compiler: gcc
            compiler-version: 11
            additional-dep: "g++-11"
          - compiler: gcc
            compiler-version: 12
          - compiler: gcc
            compiler-version: 14
    name: "${{ github.job }} (${{ matrix.compiler }}-${{ matrix.compiler-version }})"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build pipx ${{ matrix.additional-dep }}
      - name: Install Conan 
        run: |
          pipx install conan
          conan profile detect
      - name: Compile
        run: |
          if [[ "${{ matrix.compiler }}" == "llvm" ]]; then
            export CC=clang-${{ matrix.compiler-version }}
            export CXX=clang++-${{ matrix.compiler-version }}
          elif [[ "${{ matrix.compiler }}" == "gcc" ]]; then
            export CC=gcc-${{ matrix.compiler-version }}
            export CXX=g++-${{ matrix.compiler-version }}
          fi
          sudo ln -s $(which ccache) /usr/local/bin/$CC
          sudo ln -s $(which ccache) /usr/local/bin/$CXX
          $CXX --version
          conan build . --build=missing -s compiler.cppstd=gnu20
